### ISSUE TITLE
where art thou goldy

### ISSUE THREAD

**Issue by spifory** [mov-cli/arch-packages#1]

**Comment by THEGOLDENPRO** [comment]
Huh, what do you mean? Rephrase please

**Comment by spifory** [comment]
Nothing, you can delete this issue, was just checking to see you were still there :)

**Comment by THEGOLDENPRO** [comment]
> Nothing, you can delete this issue, was just checking to see you were still there :)

Yeah I'm still alive lmao, I'm just in the middle of taking a break from things like Discord as I want the least distraction this month. I'll probably be back later next month.

**Comment by spifory** [comment]
Not a problem, all the best!
